### ISSUE TITLE
[Bug]: Error getting prompts to prompts.zip

### ISSUE THREAD

**Issue by michalmar** [microsoft/graphrag#1005]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

I am following 2-Adavnced-getting-started.ipynb and `generate_prompts(storage_name=storage_name, limit=1, zip_file_name="prompts.zip")` fails getting prompt from APIM request:

Error:
```
Error generating prompts for data in 'my-container'. Please try a lower limit.
```

### Steps to reproduce

I am following 

Error:
```
Error generating prompts for data in 'my-container'. Please try a lower limit.
```

### Expected Behavior

I would download the prompts to local folder.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by jgbradley1** [comment]
Hi @michalmark, I think your question is related to the solution accelerator (and not the graphrag library specifically). I have seen this issue before.

In our testing, we believe it is due to the fact that the APIM service that gets deployed by default is set to use a `Developer` tier sku. The `Developer` tier has no SLA and therefore, intermittent connection issues between APIM and the client that initiated the API request (you) can occur.

When/if you deploy the solution accelerator and modify the APIM Tier to use the newer `StandardV2` sku, this issue does not show up for me. Just be aware that `StandardV2` cost more and is the reason why we have the default set to `Developer`.

If you want to use the prompt tuning API endpoint with an APIM deployment based on the `Developer` tier, I usually have success by rerunning the notebook cell that generates the prompts a few times.

**Comment by michalmar** [comment]
Yes, in my case its `Developer` and the issue is persistent, a.k.a. even after multiple tries I am getting this error. 

However, I was able to use workaround when i manually created the  prompt files  with `graphrag.index --init` command.
