### ISSUE TITLE
[Feature Request]: All workflows completed successfully.but graph embedding is null

### ISSUE THREAD

**Issue by Redhair957** [microsoft/graphrag#1542]
### Do you need to file an issue?

- [x] I have searched the existing issues and this feature is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

**Comment by natoverse** [comment]
Graph embeddings are only used if you want to perform visualization, in which case we turn on embed_graph.enabled and umap.enabled in settings.yml. Doing this will result in "real" x/y positions in your create_final_nodes.parquet, otherwise they will be set to 0,0.

Is this what you are looking for?

**Comment by Redhair957** [comment]
thanks
