### ISSUE TITLE
About language

### ISSUE THREAD

**Issue by mc112611** [microsoft/graphrag#371]
what language does GraphRAG support?   Can I use Japanese document to do RAG？

**Comment by eyast** [comment]
I believe so. GraphRAG makes calls to an OpenAI or AzureOpenAI LLM, and they support Japanese in their tokenizers. Keep in mind that the instructions (and examples) provided to the LLM to do entity extraction and summarization are all in English. You might want to modify these prompts.

For example, when you intiate the indexer, you will see prompts in `prompts\entity_extraction.txt`. Line 20 says "Return output in English". You might want to modify this so that the result is returned in Japanese.

**Comment by mc112611** [comment]
> I believe so. GraphRAG makes calls to an OpenAI or AzureOpenAI LLM, and they support Japanese in their tokenizers. Keep in mind that the instructions (and examples) provided to the LLM to do entity extraction and summarization are all in English. You might want to modify these prompts.
> 
> For example, when you intiate the indexer, you will see prompts in `prompts\entity_extraction.txt`. Line 20 says "Return output in English". You might want to modify this so that the result is returned in Japanese.

Thank you so much ， hope this project will support local LLM， not only chatGPT。

**Comment by jgbradley1** [comment]
> Thank you so much ， hope this project will support local LLM， not only chatGPT。

We welcome contributions from the community 😉 .

**Comment by natoverse** [comment]
Consolidating language support issues here: #696

**Comment by ahouse73** [comment]
> Thank you so much ， hope this project will support local LLM， not only chatGPT。

You can use local LLMs, Ollama [supports the OpenAI api specification](https://ollama.com/blog/openai-compatibility). If you set the base url of the `settings.yaml` to the Ollama api url you can use the model.

Example for the LLM:
```
llm:
  api_key: None
  type: openai_chat 
  model: mistral:latest
  model_supports_json: true
  api_base: http://localhost:11434/v1
```

**Comment by mc112611** [comment]
> > 非常感谢，希望这个项目将支持当地的LLM，而不仅仅是chatGPT .
> 
> 你可以使用本地的LLM，Ollama[支持OpenAI api规范](https://ollama.com/blog/openai-compatibility)。如果您设置了`settings.yaml`到Ollama api url，您可以使用该模型。
> 
> LLM的示例:
> 
> ```
> llm:
>   api_key: None
>   type: openai_chat 
>   model: mistral:latest
>   model_supports_json: true
>   api_base: http://localhost:11434/v1
> ```
This is very helpful. Thank you
