### ISSUE TITLE
large costs to run

### ISSUE THREAD

**Issue by brian316** [microsoft/graphrag#385]
can we let people know the basic example with one text file costs 5$ to run using openai key

**Comment by bmaltais** [comment]
Yeah. I made the mistake to try to run it on 10 documents and was blessed with a 35$ spend. I switched to use local and gpt3.5-turbo to cut cost… but results are not as good.

**Comment by DanKoan** [comment]
It cost me $3.40 to tokenize one document with a total word count of 5900 words (not including the subsequent inquiry).

**Comment by AlonsoGuevara** [comment]
Hi,

Thanks for the feedback, will make sure to include a note in the documentation!
As we understand the cost argument for developing/testing we have found the OSS models, in their current state, lead to more noise and less quality in results, our aim was for precision when building the knowledge graph hence that's why we support gpt-4 family in Azure and OAI out of the box.

However, we encourage testing with other models. There's a couple of very interesting threads like #339 and #374 where people are sharing their configurations and getting really nice results :)

**Comment by adieyal** [comment]
I changed gpt-4 to gpt-4o which is half the price. the 33000 word Christmas Carol example  cost around $2.5 with excellent results. Not the cheapest but half the price of the default gpt-4 model. Depending on your use case, the cost might acceptable.
