### ISSUE TITLE
python -m graphrag.index --init --root ./ragtest issue

### ISSUE THREAD

**Issue by jachenms** [microsoft/graphrag#438]
![image](https://github.com/microsoft/graphrag/assets/155041854/bdd9407c-20ad-49b9-861c-ee379183a4dc)
<img width="1080" alt="graphragissue" src="https://github.com/microsoft/graphrag/assets/155041854/98f71d59-e978-4187-a590-f9a21b3509b5">
[indexing-engine.log](https://github.com/user-attachments/files/16130639/indexing-engine.log)
 
please help me to solve the issue, why always happen.

**Comment by stevetru1** [comment]
Most likely the input you are submitting is not utf-8 formatted due to the way you downloaded it.  This package is meant to run on linux and there are some odd filesystem related issues like this that can crop up on Windows and MacOS where plain text is not truly plain text.

You can try something like this in powershell `Invoke-WebRequest -Uri https://url/ -OutFile "C:\path\file"` to download, although the better way would be to use WSL.

**Comment by jachenms** [comment]
This issue have been solved , thanks a lot, you are really expert. keep in touch

**Comment by acondess** [comment]
I solved this same issue by changing  book.txt's  file property  Ecoding to utf-8。
![image](https://github.com/microsoft/graphrag/assets/8872356/c58894b4-aa44-4910-96c0-73a77b9bd1aa)

**Comment by AlonsoGuevara** [comment]
Amazing.
I'm currently working on a fix to make sure everything is stored in utf-8.

Thabks for your updates
