### ISSUE TITLE
[  note: This error originates from a subprocess, and is likely not a problem with pip.   ERROR: Failed building wheel for gensim Failed to build fastparquet gensim ERROR: Could not build wheels for fastparquet, gensim, which is required to install pyproject.toml-based projects]: <error while installing graphrag> 

### ISSUE THREAD

**Issue by mohibahmedbleedai** [microsoft/graphrag#607]
### Describe the issue

getting the above error while installing graphrag. even when I manually try  to install fastparquet, gensim still same issue.

### Steps to reproduce

pip install graphrag

### Logs and screenshots

![image](https://github.com/user-attachments/assets/1f8ceb05-2445-40a3-b1b0-0437f4e1742a)

### Additional Information

- GraphRAG Version:
- Operating System: windows
- Python Version: 3.12.4
- Related Issues:

**Comment by jgbradley1** [comment]
Can you create a brand new virtual environment and re-install? If you had trouble installing `fastparquet` and `gensim` manually, the issue is in your local environment and not the `graphrag` package. I would suggest researching how these packages are installed in a Windows environment in case there are external dependencies that you're missing (and therefore causing these package installs to fail).
