### ISSUE TITLE
[Feature Request]: <Would there be any more input files format choice?>

### ISSUE THREAD

**Issue by Bai1026** [microsoft/graphrag#610]
### Is your feature request related to a problem? Please describe.

Not really a problem, just wanna know whether there would be more input file format choice instead of only txt and csv files, I think lot of the files would be json format. Hope this could be implemented~
Unless the performance of directly transforming the json file into txt file remains the same lol.
BTW, thx for your developing, this approach is quite useful and insightful!

**Comment by jgbradley1** [comment]
At this time, we are not prioritizing adding support for other text-based file formats (like JSON) just because there are so many out there for different use-cases and across different domains that it would be hard to maintain support for.

Instead, this task is a data transformation preprocessing step which we leave up to the end-user to implement based on whatever constraints their environment/system has.

**Comment by jackiezhangcn** [comment]
but for some table information, it's hard to convert, any tips there?
