### ISSUE TITLE
global search find a issue

### ISSUE THREAD

**Issue by ayanami108** [microsoft/graphrag#627]
### Describe the issue

site-packages\graphrag\query\structured_search\global_search\search.py", line 200, in _map_response_single_batch,i print search_response,and describe like this:

Please provide me with the story so I can identify the top themes.

how can i fix this?

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by seadirt** [comment]
same issue

**Comment by KashunCheng** [comment]
The issue is likely due to the insufficient context window of your local LLM instance, causing it to be unable to read the entire prompt. If you are using Ollama, you can try increasing the `num_ctx` parameter. Refer to the [Ollama Model File Documentation](https://github.com/ollama/ollama/blob/main/docs/modelfile.md) to create a new model with a larger `num_ctx`.

Additionally, see the related issue https://github.com/ollama/ollama/issues/2653 for more information.

**Comment by natoverse** [comment]
Consolidating alternate model issues here: https://github.com/microsoft/graphrag/issues/657
