### ISSUE TITLE
[Issue]: <Entity Extraction Question> 

### ISSUE THREAD

**Issue by Bai1026** [microsoft/graphrag#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

Actually nothing is wrong, but while I was testing the graphRAG with my own chat log dataset, it could successfully answer the question I want (e.g. give some most used word of Vincent in the chat log). 

And then I go to check the graphml and parquet files, I could not find these entities, these entities is like some specific word (something like damn, oops... but in Chinese).

**I am wondering how is it possible if the entities is not extracted but the local search could answer the questions successfully.**

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
In the response, the LLM should print citations for the entities and relationships used (e.g., "Entities(id1,id2,...)"). You can look up those entities in the create_final_entities.parquet and match on the human readable id field.

So: can you check your outputs and see if this aligns? If you have an entity id cited that is not in the parquet, this may be a hallucination example.

Otherwise: We try with our prompts to force the LLM to only rely on the supplied entity list to answer the question, but it is possible that it is drawing on its training to answer the question.

You also mention that the language is Chinese - we are tracking non-English with a consolidated issue; folks have various comments on how to get better results: https://github.com/microsoft/graphrag/issues/696
