### ISSUE TITLE
Why is Graph-RAG more expensive and less effective(namely, slower)? 

### ISSUE THREAD

**Issue by JOY-SWang** [microsoft/graphrag#750]
Why is Graph-RAG more expensive and less effective(namely, slower)? Does it have to search the whole graph for each query? 

理论上难道不是建立了知识图谱，去索引的时候，会更高效吗？还是每次查整个knowledge graph还要很久？

**Comment by KylinMountain** [comment]
其实只有全局查询慢，局部查询挺快的 但需要流式输出才行，响应很快。我已经开发出来了。

**Comment by natoverse** [comment]
Yes, as @KylinMountain notes, global search is slower and more expensive and local search is usually faster and less expensive. I discuss this a bit more in #721, and the global search algorithm is also discussed in detail in the arxiv paper. In short, global search does a lot more summarization, so it requires many more LLM calls

**Comment by Xiyuche** [comment]
> 其实只有全局查询慢，局部查询挺快的 但需要流式输出才行，响应很快。我已经开发出来了。

大约能做到多快呢？我使用了一本80k字数的汉字书籍，qwen-plus，每次对概念提问的回复大约都需要1分钟左右才能完成输出。

**Comment by KylinMountain** [comment]
> > 其实只有全局查询慢，局部查询挺快的 但需要流式输出才行，响应很快。我已经开发出来了。
> 
> 大约能做到多快呢？我使用了一本80k字数的汉字书籍，qwen-plus，每次对概念提问的回复大约都需要1分钟左右才能完成输出。

local question it will stream output instantly, you can check my video in bilibili.com. https://www.bilibili.com/video/BV113v8e6EZn/?vd_source=e3cbf0ac6779ce544ca98ef21d25c413

global question about 12-15 seconds and then streaming ouput, but this may take long due to your reports size.


你试试吧，本地查询基本秒出
