### ISSUE TITLE
[Issue]: If I have already index a .txt file, can I still index a .csv file and merge it to the existing graph?

### ISSUE THREAD

**Issue by Edwin-poying** [microsoft/graphrag#784]
Hi, I have questions about the following situations:
1. If I have already index a .txt file, can I still index a .csv file and merge it to the existing graph?
2. Can I indexing both csv and txt file at the same time?

Thanks

**Comment by natoverse** [comment]
I don't think this will work as it currently stands. Incremental ingest (see #741) currently works because it takes advantage of the cache: you can add new files, but prior files are still read; they just get the benefit of the cache for processing to avoid expensive recompute (to a point). In this case, however, you have to update your reader config such that the ingest won't even look for those originals because they are of a different type. At the moment my suggestion would be a pre-processing script to get the new files in the same format, but I'll add a note to the incremental issue that we should take this use case into consideration.

**Comment by natoverse** [comment]
For the second part of your question, no, the config only supports one file type at a time.

**Comment by Edwin-poying** [comment]
I see,
Thank You @natoverse
