### ISSUE TITLE
Chaning Input Files? How to do without having data from previous input file?

### ISSUE THREAD

**Issue by davidgross631** [microsoft/graphrag#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [x] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

I've been running GraphRAG and playing around with it this morning and yesterday and I have realized that there's an issue when it comes to loading new input files. Even by completely getting rid of the content for "A Christmas Carol", replacing it with a new file and/or new content, encoding it, and then running the pipeline again, it still generates knowledge graph data for "A Christmas Carol". What's even weirder is that it still has some data about the new content I put in the input file, but still has overwhelmingly the content from "A Christmas Carol". I've restarted and retried multiple times as well. Has this ever happened to any of y'all?

The reason I have data from "A Christmas Carol" is because I've been using this guide: 
https://microsoft.github.io/graphrag/posts/get_started/

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
Interesting. One thought is that because we aggressively cache the LLM responses, it could be getting cache hits on the new content if the parameters match.

One thing to try would be to delete the `cache` folder in your workspace, or start a new workspace altogether.

There are several potential areas that this could be happening if it is a cache hit; we'll review the steps. For example, it could be skipping entity extraction from your new text units if there is an ID match and therefore saving existing (old) entities, or it could be including old entities in the community summarization later, alongside new entities.
