### ISSUE TITLE
[Issue]: Can multiple model instances be called concurrently to construct a graph？

### ISSUE THREAD

**Issue by c0derm4n** [microsoft/graphrag#949]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

The speed of constructing graphs is too slow now, especially when using larger local models

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
We have a number of settings in GraphRAG to tune parallelization and token consumption, but they assume you are working with a single API endpoint. You can add `llm` config blocks to any step and pass in new config which may help, but more generally I think you're looking for a load-balancing system that spreads requests across multiple endpoints within a single verb. We don't plan to support this specifically because it is more of an infrastructure concern. I would suggest the use of a proxy or gateway that can do this without GraphRAG needing to be aware.
